"""add user_id to books and reviews

Revision ID: 755e6070e876
Revises: c0adf307de24
Create Date: 2026-02-21 12:09:09.177793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755e6070e876'
down_revision: Union[str, Sequence[str], None] = 'c0adf307de24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('books', sa.Column('is_favorite', sa.Boolean(), server_default='0', nullable=True))
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.add_column('reviews', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('reviews', sa.Column('child_age_months', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_column('reviews', 'child_age_months')
    op.drop_column('reviews', 'user_id')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_column('books', 'is_favorite')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
