"""add_activity_and_language_fields

Revision ID: c0adf307de24
Revises: bb322c2842ea
Create Date: 2026-02-16 09:41:27.861971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0adf307de24'
down_revision: Union[str, Sequence[str], None] = 'bb322c2842ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'activity')
    op.drop_column('books', 'language')
    # ### end Alembic commands ###
